# Generated by Django 3.0.3 on 2020-06-30 06:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(default='booking/images/blank.png', upload_to='booking/images')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField(blank=True, null=True)),
                ('close_at', models.TimeField(blank=True, null=True)),
                ('days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True)),
                ('audiname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Auditorium')),
            ],
            options={
                'unique_together': {('audiname', 'start_at', 'close_at', 'days')},
            },
        ),
    ]
