# Generated by Django 3.0.3 on 2020-06-30 10:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('eventname', models.CharField(blank=True, max_length=200, null=True)),
                ('eventdesc', models.CharField(blank=True, max_length=300, null=True)),
                ('eventdate', models.DateField(blank=True, null=True)),
                ('eventexp', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.SmallIntegerField(blank=True, default=0, max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=57, null=True),
        ),
    ]
